package zero.model;
// Generated Jul 27, 2017 3:47:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Song generated by hbm2java
 */
@Entity
@Table(name = "song", catalog = "zero")
public class Song implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 856530776835217640L;
	private Integer id;
	private String path;
	private String shortName;
	private String title;
	private String artist;
	private int length;
	private double size;
	private String bitRate;
	private String type;

	public Song() {
	}

	public Song(String path, String shortName, String title, String artist, int length, double size, String bitRate,
			String type) {
		this.path = path;
		this.shortName = shortName;
		this.title = title;
		this.artist = artist;
		this.length = length;
		this.size = size;
		this.bitRate = bitRate;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "path", nullable = false, length = 1000)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "short_name", nullable = false, length = 100)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "title", nullable = false, length = 500)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "artist", nullable = false, length = 100)
	public String getArtist() {
		return this.artist;
	}

	public void setArtist(String artist) {
		this.artist = artist;
	}

	@Column(name = "length", nullable = false)
	public int getLength() {
		return this.length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	@Column(name = "size", nullable = false, precision = 22, scale = 0)
	public double getSize() {
		return this.size;
	}

	public void setSize(double size) {
		this.size = size;
	}

	@Column(name = "bit_rate", nullable = false, length = 20)
	public String getBitRate() {
		return this.bitRate;
	}

	public void setBitRate(String bitRate) {
		this.bitRate = bitRate;
	}

	@Column(name = "type", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
