#!/usr/bin/env ksh
#@##############################################################################
#@#
#@#   File: delete_variable
#@#   $Date: 2013/04/23 13:53:16 $
#@#   $Revision: 1.9 $
#@#   Description: Delete variable from the response file
#@#   Delete variable from the response file under $IMX_CLT/cms/rsp/instance.rsp 
#@#   as creates backup before the deletion.
#@#   Example:
#@#     delete_variable IMX_HOME
#@#
#@##############################################################################

STARTDIR=$(pwd)
cd $(dirname $(whence $0))
BINDIR=$(pwd)
cd $STARTDIR

export OUTPUT=${OUTPUT:-TRUE}

# Load functions
[[ -f ${BINDIR}/functions ]] && . ${BINDIR}/functions || . ${IMX_SYSADM:-$IMX_HOME/sysadm}/functions

# Set log level
LOGLEVEL=${DEBUGLEVEL:-5}


[[ -f ${BINDIR}/.env ]] && . ${BINDIR}/.env		#Obsolete, tobe removed
[[ -f ${BINDIR}/cms.env ]] && . ${BINDIR}/cms.env
[[ -f ${IMX_CLT}/config/sysadm/cms/cms.conf ]] && . ${IMX_CLT}/config/sysadm/cms/cms.conf
[[ -f ${IMX_CLT}/config/sysadm/cms/${PROG_NAME}.conf ]] && . ${IMX_CLT}/config/sysadm/cms/${PROG_NAME}.conf

##======================##

[[ -z $IMX_CLT ]] && error "Incorrect environment! \$IMX_CLT not specified."

display "\n${BOLD}Change instance configuration${_BOLD}\n"

VARNAME="$(print $1 | awk -F'=' '{print $1}')"

[[ -z "$VARNAME" ]] && error "Please define variable to be deleted"

set_action_msg "Backup"
execute 2 "cp $RESPONSE_DIR/instance.rsp $RESPONSE_DIR/instance.rsp_${UNIQUE_ID}"
check_exit_code
display

set_action_msg "Deleting"
execute 2 "print '/^${VARNAME}=/d\nw' | ed -s $RESPONSE_DIR/instance.rsp"
check_exit_code 'checkExistNOK "^\?$"'
display

exit $RC
