#!/usr/bin/env ksh
#@##############################################################################
#@#
#@#   File: list_config
#@#   $Date: 2013/01/09 10:31:00 $
#@#   $Revision: 1.8 $
#@#   Description: List all config files that contains specific variable
#@#                
#@#   Shows all configuration files that contain specific variable as search
#@#   for it in templates
#@#   Example:
#@#     list_config IMX_HOME
#@#
#@##############################################################################

STARTDIR=$(pwd)
cd $(dirname $(whence $0))
BINDIR=$(pwd)
cd $STARTDIR

export OUTPUT=${OUTPUT:-TRUE}

# Load functions
[[ -f ${BINDIR}/functions ]] && . ${BINDIR}/functions || . ${IMX_SYSADM:-$IMX_HOME/sysadm}/functions

# Set log level
LOGLEVEL=${DEBUGLEVEL:-5}


[[ -f ${BINDIR}/.env ]] && . ${BINDIR}/.env		#Obsolete, tobe removed
[[ -f ${BINDIR}/cms.env ]] && . ${BINDIR}/cms.env 
[[ -f ${IMX_CLT}/config/sysadm/cms/cms.conf ]] && . ${IMX_CLT}/config/sysadm/cms/cms.conf
[[ -f ${IMX_CLT}/config/sysadm/cms/${PROG_NAME}.conf ]] && . ${IMX_CLT}/config/sysadm/cms/${PROG_NAME}.conf

##======================##

export QUIET="TRUE"

[[ -z $IMX_CLT ]] && error "Incorrect environment! \$IMX_CLT not specified."

display "\n${BOLD}Get instance configuration${_BOLD}\n"

VARNAME="$(print $1 | awk -F'=' '{print $1}')"

[[ -z "$VARNAME" ]] && error "Please define variable to be checked"

set_action_msg "Getting"
execute 3 "egrep "^$VARNAME=" $RESPONSE_DIR/instance.rsp"
check_exit_code
display
getCommandOut | awk -F'=' '{print $2}'


exit $RC
